project:
  type: website
  output-dir: _site

website:
  title: "Introduction to Computational Neuroscience with Neun"
  sidebar:
    style: "docked"
    background: primary
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Part 1: Computational Neuroscience"
        file: 01-intro-compneuro.qmd
      - section: "Part 2: Simulations with Neun"
        contents:
        - text: "Intro to Neun"
          file: 02-01-neun-basics.qmd
        - text: "Neurons"
          file: 02-02-single-neurons.qmd
        - text: "Synapsis & Networks"
          file: 02-03-neural-networks.qmd
      - text: "Part 3: Analysis and Visualization"
        file: 04-neural-networks.qmd
      - text: "Part 4: Conclusions"
        file: 05-conclusions.qmd
      - text: "---"
      - text: "Neun GitHub"
        icon: github
        href: https://github.com/GNB-UAM/Neun/

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    code-copy: true

execute:
  freeze: auto
  cache: true
  warning: false
  message: false
